### ISSUE TITLE
イントロダクションのcitiationとはの画像が表示されない

### ISSUE THREAD

**Issue by re-taro** [citation-dev/citation.m2en.dev#4]
## 概要

イントロダクションのcitiationとはの画像が以下のように表示されない。
![image](https://user-images.githubusercontent.com/68799469/201463311-5de6cf35-ec9b-4ecd-81c6-898ee1318fa6.png)

## 理由

https://github.com/citation-dev/citation/pull/109 のPRで下の箇所のパスが修正されていないからだと思います。

https://github.com/citation-dev/citation.m2en.dev/blame/ac9b4cbf486a688eec56ba7fab899bd438249d92/src/guide/README.md?plain=1#L13

## 対象ページ

https://citation.m2en.dev/guide/#citation-%E3%81%A8%E3%81%AF

**Comment by m2en** [comment]
修正しました
Thank you ❤
